### ISSUE TITLE
Implement dynamic operator sets

### ISSUE THREAD

**Issue by Swopper050** [AdvancedClimateSystems/gonnx#190]
Right now, by our design we have separate folder for every opset, like `ops/opset13/*`. However, most operators don't change over opsets. It would be better to create opsets based on the 'closest lower' operator version. I.e. for opset 13, if the `Conv` operator changed last in opset 7, we should take the `Conv` operator from opset 7.

This requires some refactoring but it will save a lot of duplicate code.

**Comment by Asquator** [comment]
Is it so difficult to implement? It's one of the main issues that prevents gonnx from properly working with sklearn-to-onnx.
They, on their side,[ fail to force the required opset import in the metadata](https://github.com/onnx/sklearn-onnx/issues/1096), which causes troubles.

**Comment by Swopper050** [comment]
@Asquator thanks for checking out the repo!

 I don't think it should be too difficult to implement. I will start working on it soon.
