### ISSUE TITLE
Unsqueeze operator: expected 2 input tensors, got 1

### ISSUE THREAD

**Issue by RJKeevil** [AdvancedClimateSystems/gonnx#214]
Hi, I'm working on adding gonnx to Hugot here https://github.com/knights-analytics/hugot/issues/59 .  Once I override the opset check one model that should theoretically work already is https://huggingface.co/KnightsAnalytics/distilbert-base-uncased-finetuned-sst-2-english , which is opset 11.

When i run the unit tests I get the error unsqueeze operator: expected 2 input tensors, got 1.  The input tensor map looks correct and the model has loaded fine so i thik the error must be passing the axis to this operator inside gonnx? Are you able to take a look?

I also see the same error on the https://huggingface.co/KnightsAnalytics/distilbert-NER tests, so this fix may hopefully get 2 of the 5 tests models working correctly.

**Comment by Swopper050** [comment]
Hi @RJKeevil , I'll have a look! I was trying to run the tests of hugot locally on the `alt-backends` branch to see if I could reproduce your runs mentioned [here](https://github.com/knights-analytics/hugot/issues/59), but still working on this. I'll let you know once I know more.

**Comment by Swopper050** [comment]
@RJKeevil, I've [taken a look](https://onnx.ai/onnx/operators/onnx__Unsqueeze.html), and the `Unsqueeze` operator has different implementations for opset 11 versus opset 13. 

Opset 11 has 1 input and axes as attributes
Opset 13 has 2 inputs with axes as additional input

We have implemented Unsqueeze operator version 13 right now

I think this is causing the error.

<hr />

You could either [convert](https://github.com/OpenPPL/ppl.nn/blob/master/docs/en/onnx-model-opset-convert-guide.md) the model to opset 13, that worked okey for me so far

We are definitely planning on implementing the different opset versions in a better way in [this issue ](https://github.com/AdvancedClimateSystems/gonnx/issues/190), but that still takes some work.

**Comment by RJKeevil** [comment]
Ah ok, makes total sense.  Was just overriding opset checks as a test, but I didnt appreciate it also includes behaviour changes to earlier operators.  I might have a look to see theres a way to do model conversion to v13 in hugot for now.
